name: Sort and Check Rtx Conf file

on: [push, pull_request]

jobs:
  sort-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run python unit tests
        run: |
          cd scripts
          python -m unittest test_sort_rtx_conf.py

      - name: Sort lines in rtx.conf
        run: |
          python scripts/sort_rtx_conf.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Clean Rtx Conf Bot'
          git config --global user.email 'auto-sort-bot@example.com'
          git add ./rtx.conf
          git diff --staged --exit-code || (git commit -m "Clean up rtx.conf" && git push)
