name: Sort and Check Rtx Conf file

on: [push, pull_request]

jobs:
  sort_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Sort file and
        id: sort_file
        run: |
          set -x
          git diff --word-diff=porcelain HEAD^ HEAD > /tmp/changes.txt

          cat ./rtx.conf | grep -v '^\s*#' | grep . | sort > /tmp/sorted_rtx.conf
          grep -E -- '-?0x[0-9a-fA-F]{8}' /tmp/changes.txt >> /tmp/sorted_rtx.conf

          cat /tmp/sorted_rtx.conf > ./rtx.conf

      - name: Check for changes in specific lines
        run: |
          changed=$(cat /tmp/changes.txt | grep "^+" && cat /tmp/changes.txt | grep "-")
          if [ -z "$changed" ]; then
            echo "No changes found in specific lines."
          else
            echo "Changes detected in specific lines:"
            echo "$changed"
          fi
          exit 0
