name: Sort and Check Rtx Conf file

on:
  pull_request:
    branches:
      - main

jobs:
  sort-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run python unit tests
        run: |
          cd scripts
          python -m unittest test_sort_rtx_conf.py

      - name: Sort lines in rtx.conf
        id: results_output
        run: |
          output=$(python scripts/sort_rtx_conf.py)
          echo "output=$output" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Clean Rtx Conf Bot'
          git config --global user.email 'auto-sort-bot@example.com'
          git add ./rtx.conf
          git diff --staged --exit-code || (git commit -m "Clean up rtx.conf" && git push origin ${{ github.event.pull_request.head.ref }})

      - name: Generate diff
        id: changes_output
        run: |
          curl -o old_rtx.conf https://raw.githubusercontent.com/CattoSalad/VTMB-RTX-Remix/main/rtx.conf
          {
            echo 'DIFF_OUTPUT<<EOF'
            python scripts/generate_diff.py
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Changes:
            ${{ steps.changes_output.outputs.diff_output }}
